### ISSUE TITLE
Autogenerate all of the API wrappings

### ISSUE THREAD

**Issue by leonerd** [goodmind/telegram-mt-node#14]
It would be nice if, rather than having to manually write every method wrapping an API function, that they were all automatically generated. We only have a tiny fraction of the full API wrapped, so adding more of them is tedious manual work.

I suspect it wouldn't be too hard to do this given as the types are all nicely wrapped.

**Comment by goodmind** [comment]
Isn't this issue should be in telegram.link?

**Comment by leonerd** [comment]
Doh; probably yes. Sorry - getting the layerings muddled in my head.
